/* filename: quit.pl */
/* Melakukan quit dengan retract semua dynamic value */
quit :-
    retractall(idPlayer(_)),
    retractall(player1(_)),
    retractall(player2(_)),
    retractall(turn(_)),
    retractall(count(_)),
    retractall(prev(_)),
    retractall(uangPropP1(_)),
    retractall(uangPropP2(_)),
    retractall(numGetOutOfJailP1(_)),
    retractall(numGetOutOfJailP2(_)),
    retractall(listOfPropsP1(_)),
    retractall(listOfPropsP2(_)),
    retractall(listofCardsP1(_)),
    retractall(listOfPropsP2(_)),
    retractall(aksi(_)),
    retractall(jailp1(_)),
    retractall(jailp2(_)),
    retractall(uangP1(_)),
    retractall(uangP2(_)),
    retractall(propTanahP1(_)),
    retractall(propTanahP2(_)),
    retractall(propBangunan1P1(_)),
    retractall(propBangunan1P2(_)),
    retractall(propBangunan2P1(_)),
    retractall(propBangunan2P2(_)),
    retractall(propBangunan2P2(_)),
    retractall(propBangunan3P1(_)),
    retractall(propBangunan3P2(_)),
    retractall(propLandmarkP1(_)),
    retractall(propLandmarkP2(_)).