/* Filename: start.pl */
/* memulai game */
start :-
    randomize,
    asserta(player1(go)),
    asserta(player2(go)),
    asserta(turn(1)),
    asserta(aksi(2)),
    asserta(count(0)),
    asserta(prev(0)),
    asserta(jailp1(0)),
    asserta(jailp2(0)),
    asserta(idPlayer(p1)),
    asserta(idPlayer(p2)),
    asserta(uangP1(0)),
    asserta(uangP2(0)),
    asserta(uangPropP1(0)),
    asserta(uangPropP2(0)),
    asserta(listOfPropsP1([])),
    asserta(listOfPropsP2([])),
    asserta(propTanahP1([])),
    asserta(propTanahP2([])),
    asserta(propBangunan1P1([])),
    asserta(propBangunan1P2([])),
    asserta(propBangunan2P1([])),
    asserta(propBangunan2P2([])),
    asserta(propBangunan3P1([])),
    asserta(propBangunan3P2([])),
    asserta(propLandmarkP1([])),
    asserta(propLandmarkP2([])),
    asserta(listofCardsP1([])),
    asserta(listofCardsP2([])),
    asserta(numGetOutOfJailP1(0)),
    asserta(numGetOutOfJailP2(0)),
    
 write(' _    _                   ______           '),nl,
 write('| |  | |                 |  ____|          '),nl,
 write('| |__| | __ ___   _____  | |__ _   _ _ __  '),nl,
 write('|  __  |/ _` \\ \\ / / _ \\ |  __| | | | |_ \\ '),nl,
 write('| |  | | (_| |\\ V /  __/ | |  | |_| | | | |'),nl,
 write('|_|  |_|\\__,_| \\_/ \\___| |_|   \\__,_|_| |_|'),nl.